/**
 * SwarmitRegistryV2 ABI. Mirrors the full public surface of
 * contracts/src/SwarmitRegistryV2.sol: 5 events, 5 write methods,
 * and the 7 public-mapping getters auto-generated by Solidity.
 *
 * When SwarmitRegistryV2.sol changes, update this file and encode.js,
 * bump the package version, and tag. See README.md for sync discipline.
 */

export const ABI = [
  // --- events (5) ---
  'event BoardRegistered(bytes32 indexed boardId, string slug, string boardRef, address governance)',
  'event BoardMetadataUpdated(bytes32 indexed boardId, string boardRef)',
  'event SubmissionAnnounced(bytes32 indexed boardId, bytes32 indexed submissionId, bytes32 parentSubmissionId, bytes32 rootSubmissionId, address author)',
  'event CuratorDeclared(address indexed curator, string curatorProfileRef)',
  'event VoteSet(bytes32 indexed boardId, bytes32 indexed submissionId, address indexed voter, bytes32 rootSubmissionId, int8 direction, int8 previousDirection, uint64 upvotes, uint64 downvotes)',

  // --- writes (5) ---
  'function registerBoard(bytes32 boardId, string slug, string boardRef)',
  'function updateBoardMetadata(bytes32 boardId, string boardRef)',
  'function announceSubmission(bytes32 boardId, bytes32 submissionId, bytes32 parentSubmissionId, bytes32 rootSubmissionId)',
  'function setVote(bytes32 submissionId, int8 direction)',
  'function declareCurator(string curatorProfileRef)',

  // --- public state getters (7, auto-generated by Solidity from public mappings) ---
  'function boardGovernance(bytes32 boardId) view returns (address)',
  'function submissionExists(bytes32 submissionId) view returns (bool)',
  'function submissionBoard(bytes32 submissionId) view returns (bytes32)',
  'function submissionRoot(bytes32 submissionId) view returns (bytes32)',
  'function voteOf(bytes32 submissionId, address voter) view returns (int8)',
  'function upvoteCount(bytes32 submissionId) view returns (uint64)',
  'function downvoteCount(bytes32 submissionId) view returns (uint64)',
];
