/**
 * SwarmitRegistryV3 ABI. Mirrors the full public surface of
 * contracts/src/SwarmitRegistryV3.sol: 7 events, 7 write methods,
 * 7 public-mapping getters, and 7 explicit view helpers.
 *
 * When SwarmitRegistryV3.sol changes, update this file and encode.js,
 * bump the package version, and tag. See README.md for sync discipline.
 */

export const ABI = [
  // --- events (7) ---
  'event BoardRegistered(bytes32 indexed boardId, string slug, string boardRef, address governance)',
  'event BoardMetadataUpdated(bytes32 indexed boardId, string boardRef)',
  'event SubmissionAnnounced(bytes32 indexed boardId, bytes32 indexed submissionId, bytes32 parentSubmissionId, bytes32 rootSubmissionId, address author)',
  'event CuratorDeclared(address indexed curator, string curatorProfileRef)',
  'event VoteSet(bytes32 indexed boardId, bytes32 indexed submissionId, address indexed voter, bytes32 rootSubmissionId, int8 direction, int8 previousDirection, uint64 upvotes, uint64 downvotes)',
  'event UserFeedDeclared(address indexed user, bytes32 indexed feedId, bytes32 feedTopic, address feedOwner)',
  'event UserFeedRevoked(address indexed user, bytes32 indexed feedId, bytes32 feedTopic, address feedOwner)',

  // --- writes (7) ---
  'function registerBoard(string slug, string boardRef)',
  'function updateBoardMetadata(bytes32 boardId, string boardRef)',
  'function announceSubmission(bytes32 boardId, bytes32 submissionId, bytes32 parentSubmissionId, bytes32 rootSubmissionId)',
  'function setVote(bytes32 submissionId, int8 direction)',
  'function declareCurator(string curatorProfileRef)',
  'function declareUserFeed(bytes32 feedTopic, address feedOwner)',
  'function revokeUserFeed(bytes32 feedId)',

  // --- public state getters (7, auto-generated by Solidity from public mappings) ---
  'function boardGovernance(bytes32 boardId) view returns (address)',
  'function submissionExists(bytes32 submissionId) view returns (bool)',
  'function submissionBoard(bytes32 submissionId) view returns (bytes32)',
  'function submissionRoot(bytes32 submissionId) view returns (bytes32)',
  'function voteOf(bytes32 submissionId, address voter) view returns (int8)',
  'function upvoteCount(bytes32 submissionId) view returns (uint64)',
  'function downvoteCount(bytes32 submissionId) view returns (uint64)',

  // --- explicit view helpers (7) ---
  'function voteStats(bytes32 submissionId, address voter) view returns (uint64 upvotes, uint64 downvotes, int8 direction)',
  'function isValidSlug(string slug) pure returns (bool)',
  'function hasUserFeed(address user, bytes32 feedId) view returns (bool)',
  'function userFeedsOf(address user) view returns (tuple(bytes32 feedId, bytes32 feedTopic, address feedOwner)[])',
  'function userFeedCount(address user) view returns (uint256)',
  'function userFeedIdAt(address user, uint256 index) view returns (bytes32)',
  'function userFeedCoordinates(bytes32 feedId) view returns (bytes32 feedTopic, address feedOwner)',
];
